config/routes.rb
TwoCents::Application.routes.draw do
  root 'welcomes#show'

  resource :dashboard, only: [:show]
  resources :users, only: [:create]

  resources :discussions, only: [:new, :show, :create] do
    resource :discussion_status, only: [:update]
    resources :comments, only: [:create]
    resource :username, only: [:create]
  end
end

app/models/audio.rb
class Audio < ActiveRecord::Base
  has_one :discussion, as: :content, dependent: :destroy

  has_attached_file :subject,
    storage: :s3,
    bucket: ENV.fetch('S3_BUCKET_NAME'),
    s3_credentials: {
      access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
      secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY')
    }

  validates_attachment :subject, presence: true,
    size: {
      in: 0..61440.kilobytes,
      message: 'must be under 60MB in size.'
    },
    file_name: {
      matches: [
        /mp3\Z/,
        /ogg\Z/,
        /wav\Z/
      ],
      message:
        'needs to be one of these extensions: mp3, ogg, or wav.'
    }
end

app/models/code.rb
class Code < ActiveRecord::Base
  has_one :discussion, as: :content

  validate :check_if_real_gist_url

  def gist_id
    subject.split("/").last
  end

  private

  def check_if_real_gist_url
    unless subject.split("/")[2] == "gist.github.com"
      errors.add(:subject, "must be a URL from gist.github.com")
    end
  end

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :discussion
  belongs_to :user

  validates :discussion_id,
    uniqueness: { scope: :user_id }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discussion

  def self.recent
    order(created_at: :asc)
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :discussion

  validates :url, presence: true
end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  before_create :generate_token

  belongs_to :user
  belongs_to :content, polymorphic: true

  has_many :comments, dependent: :destroy
  has_many :collaborations, dependent: :destroy

  validates :name, presence: true
  validates :user, presence: true

  def self.open
    where(closed: false)
  end

  def self.closed
    where(closed: true)
  end

  def to_param
    token
  end

  def close
    update(closed: true)
  end

  def open?
    !closed
  end

  private

  def generate_token
    self.token = SecureRandom.hex(8)
    while Discussion.exists?(token: token)
      self.token = SecureRandom.hex(8)
    end
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  has_one :discussion, as: :content, dependent: :destroy

  has_attached_file :subject,
    storage: :s3,
    bucket: ENV.fetch('S3_BUCKET_NAME'),
    s3_credentials: {
      access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
      secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY')
    }

  validates_attachment :subject, presence: true,
    size: {
      in: 0..20480.kilobytes,
      message: 'must be under 20MB in size.'
    },
    file_name: {
      matches: [
        /xlsx?\Z/,
        /te?xt\Z/,
        /rtf\Z/,
        /pptx?\Z/,
        /keynote\Z/,
        /pages\Z/,
        /numbers\Z/,
        /pdf\Z/,
        /docx?\Z/
      ],
      message:
        'needs to be one of these extensions: pdf, doc(x), xls(x), t(e)xt, ppt(x), rtf, keynote, pages, or numbers.'
    }
end

app/models/guest.rb
class Guest
  attr_reader :username

  def initialize(username="")
    @username = username
  end

  def owns?(discussion)
    false
  end

  def can_collaborate?(discussion)
    false
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_one :discussion, as: :content, dependent: :destroy

  has_attached_file :subject,
    styles: { medium: '700x700>' },
    storage: :s3,
    bucket: ENV.fetch('S3_BUCKET_NAME'),
    s3_credentials: {
      access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID'),
      secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY')
    }

  validates_attachment :subject, presence: true,
    size: {
      in: 0..20480.kilobytes,
      message: 'must be under 20MB in size.'
    },
    file_name: {
      matches: [
        /gif\Z/,
        /png\Z/,
        /jpe?g\Z/
      ],
      message:
        'needs to be one of these extensions: png, gif, or jp(e)g.'
    }
end

app/models/music.rb
class Music < ActiveRecord::Base
  belongs_to :content, polymorphic: true
end

app/models/null_content_object.rb
class NullContentObject
  def url
    'You have no content'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :discussions, dependent: :destroy
  has_many :collaborations
  has_many :collaborated_discussions, through: :collaborations,
    source: :discussion

  validates :username, presence: true

  def owns?(discussion)
    discussion_ids.include? discussion.id
  end

  def can_collaborate?(discussion)
    !owns?(discussion)
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_one :discussion, as: :content

  validate :check_if_youtube_video

  def youtube_video_id
    subject.split("=")[1]
  end

  private

  def check_if_youtube_video
    unless subject.include?("youtube.com")
      errors.add(:subject, "must be a URL from YouTube")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js, :html

  def create
    discussion = find_discussion
    comment = discussion.comments.create(comment_params)
    process_comment(comment)
  end

  private

  def comment_params
    params.require(:comment).
      permit(
        :body,
        :username
      )
  end

  def find_discussion
    Discussion.find_by(token: params[:discussion_id])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  respond_to :html

  def new
    @content = Content.new
    @discussion = find_discussion
  end

  def create
    discussion = find_discussion
    @content = discussion.contents.create(content_params)
    respond_with @content, location: discussion
  end

  private

  def find_discussion
    current_user.discussions.find(params[:discussion_id])
  end

  def content_params
    params.require(:content).
      permit(
        :url
      )
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authorize, only: [:new, :create]

  def new
    @discussion_form = DiscussionForm.new
    @types = ["Image", "Document", "Code", "Video", "Audio"]
  end

  def show
    @discussion = Discussion.find_by(token: params[:id])
    @comments = @discussion.comments.recent
    @comment = Comment.new
    @content = @discussion.content
  end

  def create
    @discussion_form = DiscussionForm.new(form_params)
    @types = ["Image", "Document", "Code", "Video", "Audio"]
    if @discussion_form.valid?
      content = @discussion_form.persist
      redirect_to content.discussion
    else
      render :new
    end
  end

  private

  def form_params
    params.require(:discussion_form).
      permit(
        :name,
        :type,
        :subject
        ).
      merge(user: current_user)
  end

  def discussion_params
    params.require(:discussion).permit(:name)
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def update
    discussion = current_user.discussions.find_by(token: params[:discussion_id])
    discussion.close
    redirect_to dashboard_path
  end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
  def create
    discussion = find_discussion
    @username = set_guest_username
    redirect_to discussion
  end

  private

  def find_discussion
    Discussion.find_by(token: params[:discussion_id])
  end

  def set_guest_username
    cookies[:username] = params[:guest][:username]
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  private

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    username = user_params.delete(:username)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.username = username
    end
  end

  def user_params
    params[:user] || Hash.new
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def create

  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :goto_dashboard, if: :signed_in?

  def show
    @user = User.new
  end

  private

  def goto_dashboard
    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/discussions/_comment_form.html.erb
You are commenting as:
<% if signed_in? %>
  <%= current_user.username %>
<% else %>
  <span id="comment-username"><%= current_user.username %></span>
  <% if current_user.username.nil? %>
    <div id="comment-username-form">
      <%= form_for :guest,
        url: discussion_username_path(@discussion) do |form| %>
          <%= form.text_field :username, value: current_user.username %>
          <%= form.submit "Change" %>
      <% end %>
    </div>
  <% end %>
<% end %>
<div id="comment-form">
  <% if current_user.username %>
    <%= form_for [@discussion, @comment], remote: true do |form| %>
      <%= form.text_field :body, placeholder: "Enter your message here" %>
      <%= form.hidden_field :username, value: current_user.username %>
      <%= form.submit "Comment" %>
    <% end %>

    <% if current_user.owns?(@discussion) %>
      <div id="close-discussion-button">
        <%= button_to "Permanently Close Discussion",
             discussion_discussion_status_path(@discussion),
              method: :patch,
              confirm: 'Are you sure you want to permanently close this discussion?'
        %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/discussions/_discussion.html.erb
<div class="discussion-listing">
  <ul>
    <li><%= link_to discussion.name, discussion %></li>
  </ul>
</div>

app/views/discussions/new.html.erb
<div id="new-discussion-form">
  <p>Please select a discussion type:</p>

  <% @types.each do |type| %>
    <% if type == @discussion_form.type %>
      <button class="change-type", style="color: black;" data-type="<%= type %>">
        <%= type %>
      </button>
    <% else %>
      <button class="change-type" data-type="<%= type %>">
        <%= type %>
      </button>
    <% end %>
  <% end %>

  <%= render "error_messages", target: @discussion_form %>

  <%= form_for @discussion_form, url: discussions_path do |form| %>
    <div>
      <%= form.hidden_field :type, value: @discussion_form.type || "Image" %>
    </div>
    <div>
      <%= form.text_field :name, placeholder: "Discussion Name" %>
    </div>
    <div id="content-form-subject">
      <% if @discussion_form.type == "Video" || @discussion_form.type == "Code" %>
        <%= form.text_field :subject, id: "text-upload-button" %>
      <% else %>
        <%= form.file_field :subject, id: "file-upload-button" %>
      <% end %>
    </div>
    <%= form.submit "Submit", id: "submit-button" %>
  <% end %>
</div>

app/views/discussions/show.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('#comments').scrollTop($('#comments')[0].scrollHeight);
  });
  var pusher = new Pusher('<%= ENV.fetch('PUSHER_KEY') %>');
  var channel = pusher.subscribe('comments_updater');
  channel.bind('discussion_<%= @discussion.token %>', function(comment) {
    template = "\<span class='comment-author'\>"
    template += comment.username;
    template += " said: ";
    template += "\<\/span\>"
    var MAP = { '&': '&amp;',
                '<': '&lt;',
                '>': '&gt;',
                '"': '&quot;',
                "'": '&#39;'
              };
    var newComment = comment.body.replace(/[&<>'"]/g, function(character) {
      return MAP[character];
    });
    template += newComment;
    template += " ";
    template += moment(comment.created_at).fromNow();
    template += "\<br\>"
    $("#comments").append(template);
    $('#comments').scrollTop($('#comments')[0].scrollHeight);
  });
</script>

<div class="addthis_toolbox addthis_default_style addthis_32x32_style">
  <a class="addthis_button_preferred_1"></a>
  <a class="addthis_button_preferred_2"></a>
  <a class="addthis_button_preferred_3"></a>
  <a class="addthis_button_preferred_4"></a>
  <a class="addthis_button_compact"></a>
  <a class="addthis_counter addthis_bubble_style"></a>
</div>

<div id="discussion-name">
  <h2><%= @discussion.name %></h2>
</div>

<div id="content-wrapper">
  <%= render @discussion.content %>
</div>

<div id="comments-wrapper">
  <div id="comments">
    <%= render @comments %>
  </div>
  <% if @discussion.open? %>
    <%= render 'comment_form' %>
  <% end %>
</div>